[pytest]

testpaths = tests
python_files = test_*.py
# -n auto: Detect CPU cores and scale browsers
# --dist loadscope: Group tests by plan to prevent data collision
addopts = -n auto --alluredir=allure-results --dist loadscope --base-url http://localhost:8000